// Database types are auto-generated by Prisma
export * from '@prisma/client'

// Additional application types

export type ElectrochemistryTechnique =
  | 'CV' // Cyclic Voltammetry
  | 'EIS' // Electrochemical Impedance Spectroscopy
  | 'CA' // Chronoamperometry
  | 'CP' // Chronopotentiometry
  | 'LSV' // Linear Sweep Voltammetry
  | 'SWV' // Square Wave Voltammetry
  | 'NPV' // Normal Pulse Voltammetry
  | 'DPV' // Differential Pulse Voltammetry
  | 'BatteryCycling' // Battery Charge/Discharge Cycling
  | 'Tafel' // Tafel Analysis
  | 'OCP' // Open Circuit Potential
  | 'Unknown'

export type InstrumentType =
  | 'BioLogic'
  | 'Gamry'
  | 'Metrohm'
  | 'Neware'
  | 'Arbin'
  | 'IviumStat'
  | 'CHInstruments'
  | 'PalmSens'
  | 'Generic'

export type FileFormat =
  | 'mpt' // BioLogic text
  | 'mpr' // BioLogic binary
  | 'dta' // Gamry
  | 'csv'
  | 'txt'
  | 'xlsx'
  | 'bin'

export interface ParsedData {
  technique: ElectrochemistryTechnique
  instrument: InstrumentType
  metadata: {
    date?: Date
    settings?: Record<string, any>
    sampleInfo?: Record<string, any>
    comments?: string
  }
  data: {
    columns: string[]
    rows: number[][]
  }
  units: Record<string, string>
}

export interface PlotConfig {
  type: PlotType
  xAxis: AxisConfig
  yAxis: AxisConfig
  data: PlotData[]
  layout?: PlotlyLayout
}

export type PlotType =
  | 'cv_plot'
  | 'nyquist'
  | 'bode'
  | 'battery_cycling'
  | 'tafel'
  | 'line'
  | 'scatter'
  | 'bar'
  | 'heatmap'

export interface AxisConfig {
  column: string
  label: string
  scale: 'linear' | 'log'
  range?: [number, number]
}

export interface PlotData {
  x: number[]
  y: number[]
  type: 'scatter' | 'line' | 'bar'
  mode?: 'lines' | 'markers' | 'lines+markers'
  name?: string
  marker?: any
  line?: any
}

export interface PlotlyLayout {
  title?: string
  xaxis?: any
  yaxis?: any
  showlegend?: boolean
  hovermode?: string
  [key: string]: any
}

export interface BlockContent {
  text?: string
  level?: number
  language?: string
  checked?: boolean
  url?: string
  caption?: string
  datasetId?: string
  paperId?: string
  visualizationId?: string
  [key: string]: any
}

export interface AIMessage {
  role: 'user' | 'assistant' | 'system'
  content: string
  timestamp: Date
}

export interface WorkflowStep {
  id: string
  name: string
  description: string
  type: 'upload' | 'parse' | 'analyze' | 'visualize' | 'interpret'
  status: 'pending' | 'in_progress' | 'completed' | 'failed'
  result?: any
}

export interface AnalysisResult {
  technique: ElectrochemistryTechnique
  metrics: Record<string, number | string>
  plots: PlotConfig[]
  interpretation?: string
  suggestions?: string[]
}
